name: Reproduce

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull C++ source dependencies
      shell: bash
      run: git submodule update --init --recursive

    - name: Generate internal configs
      shell: bash
      run: cd src/main/cpp/arrow/cpp && cmake . && cd -
      
    - name: Build C++ example
      shell: bash
      run: mkdir -p build && cd build && cmake ../src/main/cpp/ && make && cd -

    - name: Run C++ example (includes generating Arrow input files for Java)
      shell: bash
      run: cd build && ./empty_list_demo && cd -

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Install Arrow snapshot to Maven local
      shell: bash
      run: cd src/main/cpp/arrow/java && mvn install && cd -

    - name: Build and run Java example
      shell: bash
      run: gradle test --info

    - name: Run C++ example again (includes reading examples from Java and previos C++ invocation)
      shell: bash
      run: cd build && ./empty_list_demo && cd -
